id: P009237
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:24.818533
source_metadata:
  id: bdr:W1CZ1310
  title: ནཱ་རོ་ཆོས་དྲུག་དང་ཁྲིད
  author: ''
  volumes:
    629b7487b47545f197938c15ab355590:
      image_group_id: I1CZ1841
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
