id: I747878A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:00:40+00:00'
last_modified: '2022-06-08T09:35:27.055788+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1310
  title: ནཱ་རོ་ཆོས་དྲུག་དང་ཁྲིད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4584':
      image_group_id: I1CZ1841
      title: ''
      total_pages: 44
      order: 1
      base_file: 4584.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
